//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class The_Applicant
    {
        public string Full_Name { get; set; }
        public long Passport_Data { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public long Phone_Number { get; set; }
        public string Place_of_Residence { get; set; }
        public int Specialization { get; set; }
        public double Average_Score { get; set; }
        public string Status { get; set; }
        public int ID { get; set; }
    
        public virtual Specialization Specialization1 { get; set; }
    }
}
